module.exports = {

    // Ticket configuration 
    ticketName: 't-',
    ticketDescription: 'Ticket open by',
    ticketCreate: '<:check:1082334169197187153> Your ticket has been created',
    ticketAlreadyExist: '<:cross:1082334173915775046> You already have an open ticket.',
    ticketNoPermissions: '<:cross:1082334173915775046> You do not have permission to do this.',
    ticketError: '<:alert:1082334164189184051> Something went wrong, try again later.',
    ticketMessageTitle: 'Welcome to your ticket.',
    ticketMessageDescription: 'Support team will be soon in contact with you.\nPlease describe your issue as detailed as possible in the meantime.',
    ticketClose: 'Close',
    ticketCloseEmoji: '📪',
    ticketLock: 'Lock',
    ticketLockEmoji: '🔒',
    ticketUnlock: 'Unlock',
    ticketUnlockEmoji: '🔓',
    ticketClaim: 'Claim',
    ticketClaimEmoji: '👋',
    ticketManage: 'Members',
    ticketManageEmoji: '➕',
    ticketManageMenuTitle: 'Select a member.',
    ticketManageMenuEmoji: '❔',
    ticketCloseTitle: 'The ticket is currently being closed...',
    ticketCloseDescription: 'Ticket will be closed in 5 seconds.',
    ticketSuccessLocked: 'Ticket was locked succesfully.',
    ticketAlreadyLocked: 'This ticket is already locked.',
    ticketSuccessUnlocked: 'Ticket was unlocked succesfully.',
    ticketAlreadyUnlocked: 'This ticket is already unlocked.',
    ticketSuccessClaim: 'Ticket was successfully claimed by',
    ticketAlreadyClaim: 'Ticket is already claimed by',
    ticketDescriptionClaim: 'and claimed by ',
    ticketTranscriptMember: 'Member',
    ticketTranscriptTicket: 'Ticket ID',
    ticketTranscriptTime: 'Time',
    ticketMemberAdd: 'has been added to the ticket.',
    ticketMemberRemove: 'has been removed to the ticket.',
}